---
title: "Data Cleaning with Excel and Python"
date: 2022-05-01
---
title: My Data Analysis Portfolio
author: Pranav
email: pranavsinha94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are going to create some awesome data analysis projects to showcase to the world.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
